name: Destroy AWS Infrastructure

on:
  workflow_dispatch:  # Manual trigger only

env:
  AWS_REGION: "af-south-1"

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: ./infrastructure

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"  # Specify your version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Check Terraform State
        run: |
          echo "=== Terraform State List ==="
          terraform state list || echo "No state found"
          echo "=== Terraform State Show ==="
          terraform show || echo "No state to show"

      - name: Show Terraform Plan (what will be destroyed)
        run: terraform plan -destroy

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

      - name: Verify destruction
        run: |
          INSTANCES=$(aws ec2 describe-instances \
            --region ${{ env.AWS_REGION }} \
            --filters "Name=tag:Project,Values=nrn" \
            --query "Reservations[].Instances[].InstanceId" \
            --output text)
          
          if [ -z "$INSTANCES" ]; then
            echo "✅ All resources destroyed."
          else
            echo "❌ Resources still exist: $INSTANCES"
            exit 1
          fi